name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: Environments
        run: npm run env
        env:
          API_URL: ${{ secrets.API_URL }}
          USERS_PATH: ${{ secrets.USERS_PATH }}
          LOGIN_PATH: ${{ secrets.LOGIN_PATH }}
          REGISTER_PATH: ${{ secrets.REGISTER_PATH }}

      - name: 🧪 Testing
        run: npm test
        env:
          API_URL: ${{ secrets.API_URL }}
          USERS_PATH: ${{ secrets.USERS_PATH }}
          LOGIN_PATH: ${{ secrets.LOGIN_PATH }}
          REGISTER_PATH: ${{ secrets.REGISTER_PATH }}
